"'Settings Screen_1' As screen":
    OnVisible: |-
        =ClearCollect(
            colSettings,
            [
            {
                'Field Name': "Dark Mode",
                Context: "Configure Dark Mode or Light Mode",
                'Input Type': "Toggle",
                'Default Value': "True",
                'Display Mode': DisplayMode.Edit
            },
            {
                'Field Name': "Large Mode",
                Context: "This is a setting that makes all the text extra large",
                'Input Type': "Toggle",
                'Default Value': "False"
            },
            {
                'Field Name': "Enter some notification text",
                Context: "",
                'Input Type': "Text",
                'Default Value': "True"
            }]);

