"'Settings Screen' As screen":
    OnVisible: |-
        =ClearCollect(
            colSettings,
            [
            {
                'Field Name': "Dark Mode",
                Context: "Configure Dark Mode or Light Mode",
                'Input Type': "Toggle",
                'Default Value': "True",
                'Display Mode': DisplayMode.Edit
            },
            {
                'Field Name': "Large Mode",
                Context: "This is a setting that makes all the text extra large",
                'Input Type': "Toggle",
                'Default Value': "False"
            },
            {
                'Field Name': "Enter some notification text",
                Context: "",
                'Input Type': "Text",
                'Default Value': "True"
            }]);

    Container5_2 As groupContainer.verticalAutoLayoutContainer:
        Height: =App.Height - Toolbar_3.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        PaddingTop: =50
        Width: =App.Width
        ZIndex: =1

        "Header_3 As 'Header With Search'":
            Fill: =Coalesce(Header_3.Properties.Colours.Background,RGBA(0,0,0,0))
            LayoutMinHeight: =640

        Settings_1 As Settings:
            FillPortions: =1
            UseModernTheming: =true
            ZIndex: =2

        Container5 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.None
            FillPortions: =0
            Height: =64
            LayoutAlignItems: =LayoutAlignItems.Center
            LayoutJustifyContent: =LayoutJustifyContent.End
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =20
            PaddingRight: =20
            ZIndex: =3

            Button1 As button:
                Color: =RGBA(255,255,255,1)
                Fill: =gvComponentTheme.Colours.Primary
                Font: =gvComponentTheme.Style.Font.'Font-Family'
                Height: =45
                LayoutMinHeight: =70
                LayoutMinWidth: =280
                OnSelect: =
                RadiusBottomLeft: =5
                RadiusBottomRight: =5
                RadiusTopLeft: =5
                RadiusTopRight: =5
                Size: =gvComponentTheme.Style.Font.Sizes.Action
                Text: ="Save"
                Width: =128
                ZIndex: =1

    Image3_2 As image:
        Height: =51
        Image: |-
            ="data:image/svg+xml;utf8, " & EncodeUrl($"
            <svg width=""{Self.Width}px"" height=""{Self.Height}px"" viewBox=""0 0 24 24"" fill=""none"" xmlns=""http://www.w3.org/2000/svg"">
            <path d=""M7.5 10V14M11.5 10V14M15.5 10V14M21 13V11M6.2 18H16.8C17.9201 18 18.4802 18 18.908 17.782C19.2843 17.5903 19.5903 17.2843 19.782 16.908C20 16.4802 20 15.9201 20 14.8V9.2C20 8.0799 20 7.51984 19.782 7.09202C19.5903 6.71569 19.2843 6.40973 18.908 6.21799C18.4802 6 17.9201 6 16.8 6H6.2C5.0799 6 4.51984 6 4.09202 6.21799C3.71569 6.40973 3.40973 6.71569 3.21799 7.09202C3 7.51984 3 8.07989 3 9.2V14.8C3 15.9201 3 16.4802 3.21799 16.908C3.40973 17.2843 3.71569 17.5903 4.09202 17.782C4.51984 18 5.07989 18 6.2 18Z"" stroke=""#555555"" stroke-width=""2"" stroke-linecap=""round"" stroke-linejoin=""round""/>
            </svg>")
        PaddingBottom: =10
        PaddingTop: =10
        Width: =58
        ZIndex: =2

    Label3_3 As label:
        Align: =Align.Right
        Color: =RGBA(85, 85, 85, 1)
        FontWeight: =FontWeight.Bold
        Height: =51
        PaddingRight: =20
        Size: =12
        Text: |-
            =Text(Now(),"hh:mm")
        Width: =560
        X: =80
        ZIndex: =3

    Toolbar_3 As Toolbar:
        Fill: =Coalesce(Toolbar_3.Properties.Controls.Gallery.Colours.Background, Toolbar_3.Properties.Colours.Background)
        Items: |-
            =[
                {
                    Title: "Home",
                    Icon: Icon.Home,
                    TargetScreen: Home
                },
                {
                    Title: "My Network",
                    Icon: Icon.People,
                    TargetScreen: Home
                },
                {
                    Title: "New Post",
                    Icon: Icon.AddDocument,
                    TargetScreen: Home
                },
                {
                    Title: "Settings",
                    Icon: Icon.Help,
                    TargetScreen: 'Settings Screen'
                },
                {
                    Title: "About",
                    Icon: Icon.LightningBolt,
                    TargetScreen: Home
                }
            ]
        Y: =App.Height - Self.Height
        ZIndex: =4

