"'App Settings' As screen":
    Fill: =gvTheme.Colours.Background
    OnVisible: =Reset(Settings_1)

    Toolbar_2 As Toolbar:
        Fill: =Coalesce(Toolbar_2.Properties.Controls.Gallery.Colours.Background, Toolbar_2.Properties.Colours.Background)
        Height: |
            =80
        Items: =colToolbarItems
        Properties: =gvTheme
        Y: =Parent.Height - Self.Height

    Container5_1 As groupContainer.verticalAutoLayoutContainer:
        Height: =App.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =App.Width
        ZIndex: =1

        Header_2 As Header:
            Fill: =Coalesce(Header_2.Properties.Colours.Background,RGBA(0,0,0,0))
            HeaderProperties: =gvHeaderProperties
            Height: =80
            LayoutMinHeight: =640
            Properties: =gvTheme
            Text: =If(Lower(Header_2.HeaderProperties.'Header Mode') = "TextInput", TextInput1_1.Text,"")
            Width: =Parent.Width

        Container6 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.None
            FillPortions: =0
            Height: |
                =64
            LayoutJustifyContent: =LayoutJustifyContent.End
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =25
            PaddingRight: =25
            PaddingTop: =10
            ZIndex: =2

            Button1 As button:
                Color: =gvTheme.Colours.Background
                Fill: =gvTheme.Colours.Primary
                Font: =gvTheme.Style.Font.'Font-Family'
                LayoutMinHeight: =70
                LayoutMinWidth: =280
                OnSelect: |-
                    =Set(gvTheme, LookUp(colThemes, ThisRecord.Name = LookUp(Settings_1.Output, ThisRecord.'Field Name' = "Theme").'New Value').Theme);
                    
                    
                    //Notify(If(Boolean(LookUp(Settings_1.Output, ThisRecord.'Field Name' = "Are you Human?").'New Value'),"You are human", "You are Robot"),NotificationType.Information)
                RadiusBottomLeft: =gvTheme.Style.Borders.Radius.BottomLeft
                RadiusBottomRight: =gvTheme.Style.Borders.Radius.BottomRight
                RadiusTopLeft: =gvTheme.Style.Borders.Radius.TopLeft
                RadiusTopRight: =gvTheme.Style.Borders.Radius.TopRight
                Size: =gvTheme.Style.Font.Sizes.Text
                Text: ="Save"
                Width: =120
                ZIndex: =1

        Settings_1 As Settings:
            FillPortions: =1
            Items: |-
                =[
                    {
                        'Field Name': "Theme",
                        Category: "Theme",
                        Context: "Choose a theme",
                        'Input Type': "Selection",
                        'Default Value': "True",
                        'Display Mode': DisplayMode.Edit,
                        Items: RenameColumns(colThemes.Name,"Name","Value")
                    },
                    {
                        'Field Name': "Are you Human?",
                        Category: "Sentient Check",
                        Context: "Define your alleigence",
                        'Input Type': "Toggle",
                        'Default Value': "True",
                        'Display Mode': DisplayMode.Edit
                    },
                    {
                        'Field Name': "Enter some text",
                        Category: "Sentient Check",
                        Context: "Type something special",
                        'Input Type': "Text",
                        'Default Value': ""
                    }]
            Properties: =gvTheme
            Width: =Parent.Width
            ZIndex: =3

