"'Sample 1 Settings' As screen":
    Fill: =gvTheme.Colours.Background
    OnVisible: =Reset(Settings_2)

    Container5_5 As groupContainer.verticalAutoLayoutContainer:
        Height: =App.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutMode: =LayoutMode.Auto
        Width: =App.Width
        ZIndex: =1

        Settings_2 As Settings:
            FillPortions: =1
            Items: |-
                =[
                    {
                        'Field Name': "Theme",
                        Category: "Theme",
                        Context: "Choose a theme",
                        'Input Type': "Selection",
                        'Default Value': "True",
                        'Display Mode': DisplayMode.Edit,
                        Items: RenameColumns(colThemes.Name,"Name","Value")
                    },
                    {
                        'Field Name': "Are you Human?",
                        Category: "Sentient Check",
                        Context: "Define your alleigence",
                        'Input Type': "Toggle",
                        'Default Value': "True",
                        'Display Mode': DisplayMode.Edit
                    },
                    {
                        'Field Name': "Enter some text",
                        Category: "Sentient Check",
                        Context: "Type something special",
                        'Input Type': "Text",
                        'Default Value': ""
                    }]
            LayoutMinWidth: =640
            Properties: =gvTheme
            Width: =Parent.Width

        Container2_6 As groupContainer.verticalAutoLayoutContainer:
            DropShadow: =DropShadow.None
            FillPortions: =0
            Height: =64
            LayoutDirection: =LayoutDirection.Vertical
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            RadiusBottomLeft: =0
            RadiusBottomRight: =0
            RadiusTopLeft: =0
            RadiusTopRight: =0
            ZIndex: =1

        Header_6 As Header:
            Fill: =Coalesce(Header_6.Properties.Colours.Background,RGBA(0,0,0,0))
            HeaderProperties: =gvHeaderProperties
            Height: =80
            LayoutMinHeight: =640
            LayoutMinWidth: =640
            Properties: =gvTheme
            Text: =If(Lower(Header_6.HeaderProperties.'Header Mode') <> "Title", txtHeaderInput.Text,"")
            Width: =Parent.Width
            ZIndex: =2

        Toolbar_6 As Toolbar:
            Fill: =Coalesce(Toolbar_6.Properties.Controls.Gallery.Colours.Background, Toolbar_6.Properties.Colours.Background)
            Height: |
                =80
            Items: =Toolbar_4.Items
            LayoutMinHeight: =640
            LayoutMinWidth: =640
            Properties: =gvTheme
            ToolbarProperties: =Toolbar_4.ToolbarProperties
            Y: =Parent.Height - Self.Height
            ZIndex: =3

        Container6_1 As groupContainer.horizontalAutoLayoutContainer:
            DropShadow: =DropShadow.None
            FillPortions: =0
            Height: |
                =64
            LayoutJustifyContent: =LayoutJustifyContent.End
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            LayoutMode: =LayoutMode.Auto
            PaddingLeft: =25
            PaddingRight: =25
            PaddingTop: =10
            ZIndex: =5

            Button1_1 As button:
                Color: =gvTheme.Colours.Background
                Fill: =gvTheme.Colours.Primary
                Font: =gvTheme.Style.Font.'Font-Family'
                LayoutMinHeight: =70
                LayoutMinWidth: =280
                OnSelect: |-
                    =Set(gvTheme, LookUp(colThemes, ThisRecord.Name = LookUp(Settings_2.Output, ThisRecord.'Field Name' = "Theme").'New Value').Theme);
                    
                    
                    //Notify(If(Boolean(LookUp(Settings_1.Output, ThisRecord.'Field Name' = "Are you Human?").'New Value'),"You are human", "You are Robot"),NotificationType.Information)
                RadiusBottomLeft: =gvTheme.Style.Borders.Radius.BottomLeft
                RadiusBottomRight: =gvTheme.Style.Borders.Radius.BottomRight
                RadiusTopLeft: =gvTheme.Style.Borders.Radius.TopLeft
                RadiusTopRight: =gvTheme.Style.Borders.Radius.TopRight
                Size: =gvTheme.Style.Font.Sizes.Text
                Text: ="Save"
                Width: =120
                ZIndex: =1

